
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-03-19T08:40:20-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ba2e79c4990d3c7a10b86308d64635c38e7619fb",
 "version": "0.6.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
